# Libraries in python

### NumPy
### Pandas
### Matplotlib

Python libraries is a collection of functions and methods that allows you to perform many actions without writing your code


## Numpy

Numpy stands for Numerical Python and is the core library for numeric and scientific computing
It consists of multidimentional array objects and a collection of routines for processing those arrays

In [3]:
# Creating NumPy array

import numpy as np
n1 = np.array([10,20,40,70,90,60])
n1

array([10, 20, 40, 70, 90, 60])

In [4]:
import numpy as np
n2 = np.array([[10,20,30,40],[50,60,70,80]])
n2

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [5]:
type(n1)

numpy.ndarray

In [6]:
# Initializing numpy arrays with zeros

import numpy as np
n1 = np.zeros((2,2))
n1

array([[0., 0.],
       [0., 0.]])

In [7]:
import numpy as np
n2 = np.zeros((5,6))
n2

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [9]:
# Initializing NumPy array with same number

import numpy as np
n1 = np.full((2,2),3)
n1

array([[3, 3],
       [3, 3]])

In [11]:
# Initializing NumPy array within a range

import numpy as np
n1 = np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [12]:
# Initializing NumPy array within a range

import numpy as np
n1 = np.arange(10,70,5)
n1

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65])

In [13]:
# Initializing NumPy array with random numbers

import numpy as np
n1 = np.random.randint(1,100,6)
n1

array([32, 15, 97, 50, 54, 91])

In [15]:
# Checking the shape of numpy arrays

import numpy as np
n1 = np.array([[1,2,3],[4,5,6]])
n1.shape

(2, 3)

In [16]:
n1.shape = (3,2)
n1.shape

(3, 2)

In [17]:
n1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
# Joining Numpy Arrays

# vstack()

import numpy as np
n1 = np.array([10,20,30])
n2 = np.array([40,50,60])

np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [19]:
# hstack()

import numpy as np
n1 = np.array([10,20,30])
n2 = np.array([40,50,60])

np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [20]:
# column_stack()

import numpy as np
n1 = np.array([10,20,30])
n2 = np.array([40,50,60])

np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [21]:
# NumPy Intersection and difference

In [25]:
import numpy as np
n1 = np.array([10,20,30,40,50])
n2 = np.array([40,50,60,70,80])
np.intersect1d(n1,n2)

array([40, 50])

In [29]:
import numpy as np
n1 = np.array([10,20,30,40,50])
n2 = np.array([40,50,60,70,80])
np.setdiff1d(n1,n2)

array([10, 20, 30])

In [30]:
import numpy as np
n1 = np.array([10,20,30,40,50])
n2 = np.array([40,50,60,70,80])
np.setdiff1d(n2,n1)

array([60, 70, 80])

## NumPy Array Mathematics

In [31]:
# Addition of NumPy arraays

import numpy as np
n1 = np.array([10,20,30,40,50])
n2 = np.array([40,50,60,70,80])
np.sum([n1,n2])

450

In [32]:
np.sum([n1,n2],axis=0)

array([ 50,  70,  90, 110, 130])

In [33]:
np.sum([n1,n2],axis=1)

array([150, 300])

In [34]:
# Basic addition

import numpy as np
n1 = np.array([10,20,30,40,50])
n1 = n1+4
n1

array([14, 24, 34, 44, 54])

In [35]:
# Basic Substraction

import numpy as np
n1 = np.array([10,20,30,40,50])
n1 = n1-4
n1

array([ 6, 16, 26, 36, 46])

In [36]:
# Basic Multiplication

import numpy as np
n1 = np.array([10,20,30,40,50])
n1 = n1*4
n1

array([ 40,  80, 120, 160, 200])

In [37]:
# Basic Division

import numpy as np
n1 = np.array([10,20,30,40,50])
n1 = n1/4
n1

array([ 2.5,  5. ,  7.5, 10. , 12.5])

In [38]:
# NumPy Math Functions

import numpy as np
n1 = np.array([10,20,30,40,50])
np.mean(n1)

30.0

In [39]:
np.std(n1)

14.142135623730951

In [40]:
np.median(n1)

30.0

In [41]:
# NumPy Array Save and Load

import numpy as np
n1 = np.array([10,20,30,40,50,60,70,80])
np.save('my_numpy',n1)

In [42]:
n2 = np.load('my_numpy.npy')
n2

array([10, 20, 30, 40, 50, 60, 70, 80])

# Analyzed by


𝐌𝐝 𝐑𝐚𝐢𝐞𝐬𝐡,
Enrollment number : 𝟏𝟗𝐔𝐌𝐄𝟏𝟏𝟔,
Registration number : 𝟏𝟗𝟏𝟏𝟑𝟒𝟓,
B Tech,7𝐭𝐡 semester,Section : 𝐀,
Mechanical Engineering Department,
National Institute of Technology Agartala, Tripura 799046
