<a href="https://www.kaggle.com/code/mdraiesh9648/numpy?scriptVersionId=108741837" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# Libraries in python

### NumPy
### Pandas
### Matplotlib

Python libraries is a collection of functions and methods that allows you to perform many actions without writing your code


## Numpy

Numpy stands for Numerical Python and is the core library for numeric and scientific computing
It consists of multidimentional array objects and a collection of routines for processing those arrays

In [1]:
# Creating NumPy array

import numpy as np
n1 = np.array([10,20,40,70,90,60])
n1

array([10, 20, 40, 70, 90, 60])

In [2]:
import numpy as np
n2 = np.array([[10,20,30,40],[50,60,70,80]])
n2

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [3]:
type(n1)

numpy.ndarray

In [4]:
# Initializing numpy arrays with zeros

import numpy as np
n1 = np.zeros((2,2))
n1

array([[0., 0.],
       [0., 0.]])

In [5]:
import numpy as np
n2 = np.zeros((5,6))
n2

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [6]:
# Initializing NumPy array with same number

import numpy as np
n1 = np.full((2,2),3)
n1

array([[3, 3],
       [3, 3]])

In [7]:
# Initializing NumPy array within a range

import numpy as np
n1 = np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [8]:
# Initializing NumPy array within a range

import numpy as np
n1 = np.arange(10,70,5)
n1

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65])

In [9]:
# Initializing NumPy array with random numbers

import numpy as np
n1 = np.random.randint(1,100,6)
n1

array([24, 56, 14, 67,  2, 28])

In [10]:
# Checking the shape of numpy arrays

import numpy as np
n1 = np.array([[1,2,3],[4,5,6]])
n1.shape

(2, 3)

In [11]:
n1.shape = (3,2)
n1.shape

(3, 2)

In [12]:
n1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
# Joining Numpy Arrays

# vstack()

import numpy as np
n1 = np.array([10,20,30])
n2 = np.array([40,50,60])

np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [14]:
# hstack()

import numpy as np
n1 = np.array([10,20,30])
n2 = np.array([40,50,60])

np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [15]:
# column_stack()

import numpy as np
n1 = np.array([10,20,30])
n2 = np.array([40,50,60])

np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [16]:
# NumPy Intersection and difference

In [17]:
import numpy as np
n1 = np.array([10,20,30,40,50])
n2 = np.array([40,50,60,70,80])
np.intersect1d(n1,n2)

array([40, 50])

In [18]:
import numpy as np
n1 = np.array([10,20,30,40,50])
n2 = np.array([40,50,60,70,80])
np.setdiff1d(n1,n2)

array([10, 20, 30])

In [19]:
import numpy as np
n1 = np.array([10,20,30,40,50])
n2 = np.array([40,50,60,70,80])
np.setdiff1d(n2,n1)

array([60, 70, 80])

## NumPy Array Mathematics

In [20]:
# Addition of NumPy arraays

import numpy as np
n1 = np.array([10,20,30,40,50])
n2 = np.array([40,50,60,70,80])
np.sum([n1,n2])

450

In [21]:
np.sum([n1,n2],axis=0)

array([ 50,  70,  90, 110, 130])

In [22]:
np.sum([n1,n2],axis=1)

array([150, 300])

In [23]:
# Basic addition

import numpy as np
n1 = np.array([10,20,30,40,50])
n1 = n1+4
n1

array([14, 24, 34, 44, 54])

In [24]:
# Basic Substraction

import numpy as np
n1 = np.array([10,20,30,40,50])
n1 = n1-4
n1

array([ 6, 16, 26, 36, 46])

In [25]:
# Basic Multiplication

import numpy as np
n1 = np.array([10,20,30,40,50])
n1 = n1*4
n1

array([ 40,  80, 120, 160, 200])

In [26]:
# Basic Division

import numpy as np
n1 = np.array([10,20,30,40,50])
n1 = n1/4
n1

array([ 2.5,  5. ,  7.5, 10. , 12.5])

In [27]:
# NumPy Math Functions

import numpy as np
n1 = np.array([10,20,30,40,50])
np.mean(n1)

30.0

In [28]:
np.std(n1)

14.142135623730951

In [29]:
np.median(n1)

30.0

In [30]:
# NumPy Array Save and Load

import numpy as np
n1 = np.array([10,20,30,40,50,60,70,80])
np.save('my_numpy',n1)

In [31]:
n2 = np.load('my_numpy.npy')
n2

array([10, 20, 30, 40, 50, 60, 70, 80])